export const createDefaultRuleSets = (generateId) => [
        { id: generateId('rs'), tag: 'geosite-category-ads-all', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ads-all.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geoip-ad', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/ad.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-youtube', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/youtube.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-category-ai-!cn', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ai-!cn.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-google', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/google.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geoip-google', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/google.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-telegram', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/telegram.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geoip-telegram', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/telegram.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-twitter', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/twitter.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geoip-twitter', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/twitter.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-netflix', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/netflix.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geoip-netflix', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/netflix.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-spotify', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/spotify.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-proxymedia', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo-lite/geosite/proxymedia.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-github', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/github.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-microsoft@cn', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/microsoft@cn.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-microsoft', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/microsoft.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-apple-cn', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/apple-cn.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-apple', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/apple.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-cn', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/cn.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geoip-cn', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/cn.srs', detour: 'direct', update_interval: '1d' },
        { id: generateId('rs'), tag: 'geosite-geolocation-!cn', format: 'binary', url: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/geolocation-!cn.srs', detour: 'direct', update_interval: '1d' },
    ];

export const createDefaultRouteRules = (generateId) => [
        { id: generateId('r'), enabled: true, name: '拦截广告', conditions: [{ type: 'rule_set', value: 'geosite-category-ads-all,geoip-ad' }], mode: 'or', invert: false, action: 'reject', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: 'YouTube', conditions: [{ type: 'rule_set', value: 'geosite-youtube' }], mode: 'and', invert: false, action: 'route', outbound: '节点选择', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: 'AI 服务', conditions: [{ type: 'rule_set', value: 'geosite-category-ai-!cn' }], mode: 'and', invert: false, action: 'route', outbound: '节点选择', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: 'Google', conditions: [{ type: 'rule_set', value: 'geosite-google,geoip-google' }], mode: 'or', invert: false, action: 'route', outbound: '节点选择', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: 'Telegram', conditions: [{ type: 'rule_set', value: 'geosite-telegram,geoip-telegram' }], mode: 'or', invert: false, action: 'route', outbound: '节点选择', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: 'Twitter / X', conditions: [{ type: 'rule_set', value: 'geosite-twitter,geoip-twitter' }], mode: 'or', invert: false, action: 'route', outbound: '节点选择', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: 'Netflix', conditions: [{ type: 'rule_set', value: 'geosite-netflix,geoip-netflix' }], mode: 'or', invert: false, action: 'route', outbound: '节点选择', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: 'Spotify', conditions: [{ type: 'rule_set', value: 'geosite-spotify' }], mode: 'and', invert: false, action: 'route', outbound: '节点选择', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: '海外流媒体', conditions: [{ type: 'rule_set', value: 'geosite-proxymedia' }], mode: 'and', invert: false, action: 'route', outbound: '节点选择', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: 'GitHub', conditions: [{ type: 'rule_set', value: 'geosite-github' }], mode: 'and', invert: false, action: 'route', outbound: '节点选择', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: '微软(国内)', conditions: [{ type: 'rule_set', value: 'geosite-microsoft@cn' }], mode: 'and', invert: false, action: 'route', outbound: 'direct', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: '微软', conditions: [{ type: 'rule_set', value: 'geosite-microsoft' }], mode: 'and', invert: false, action: 'route', outbound: '节点选择', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: 'Apple(国内)', conditions: [{ type: 'rule_set', value: 'geosite-apple-cn' }], mode: 'and', invert: false, action: 'route', outbound: 'direct', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: 'Apple', conditions: [{ type: 'rule_set', value: 'geosite-apple' }], mode: 'and', invert: false, action: 'route', outbound: '节点选择', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: '中国直连', conditions: [{ type: 'rule_set', value: 'geosite-cn,geoip-cn' }], mode: 'or', invert: false, action: 'route', outbound: 'direct', isEditing: false, draggable: false },
        { id: generateId('r'), enabled: true, name: '境外兜底代理', conditions: [{ type: 'rule_set', value: 'geosite-geolocation-!cn' }], mode: 'and', invert: false, action: 'route', outbound: '节点选择', isEditing: false, draggable: false },
    ];
